Review 1
z2511dm/cpp-peer-review pull request #2
Opened 2023-11-17 05:42 UTC by z2511dm

2023-11-20 08:32 UTC, SergeySA2023 requested changes
Хорошо. Немного надо доработать.

2023-11-20 08:32 UTC, SergeySA2023 commented on task_2.cpp
> +		DomainChecker checker(forbidden_domains.begin(), forbidden_domains.end());
Думаю будет лучше если дополнительно покрыть тестами ReadDomains.

2023-11-20 08:32 UTC, SergeySA2023 commented on task_2.cpp
> +		const std::vector<Domain> test_domains = ReadDomains(in2, 7);
in2 и test_domains не участвуют в тестах.

2023-11-20 08:32 UTC, SergeySA2023 commented on task_2.cpp
> +		assert(!checker.IsForbidden(Domain("ttt.ru")));
Если добавить assert(checker.IsForbidden(Domain("maps.com"))) то можно проверить что DomainChecker сконструирован полностью.  Т.е. ни один домен не потерян.;

2023-11-20 08:32 UTC, SergeySA2023 commented on task_2.cpp
> +	}
Лучше вывести сообщение о завершении тестирования.

2023-11-23 09:26 UTC, SergeiSA1 approved these changes

2023-11-23 09:28 UTC, merged